### ISSUE TITLE
Likely node-sass issue with Node 8.5.0 and NPM 5.4.2

### ISSUE THREAD

**Issue by zackkrida** [glimmerjs/glimmer-blueprint#64]
Tried using glimmer for the first time today and immediately hit the following wall:

```
❯ ember new glimmer-test -b @glimmer/blueprint
installing blueprint
  create .editorconfig
  create .watchmanconfig
  create README.md
  create config/environment.js
  create config/module-map.d.ts
  create config/resolver-configuration.d.ts
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create src/index.ts
  create src/main.ts
  create src/ui/components/glimmer-test/component-test.ts
  create src/ui/components/glimmer-test/component.ts
  create src/ui/components/glimmer-test/template.hbs
  create src/ui/index.html
  create src/ui/styles/app.scss
  create src/utils/test-helpers/test-helper.ts
  create testem.json
  create tsconfig.json
  create yarn.lock
Error creating new application. Removing generated directory `./glimmer-test`
Command failed: yarn install --ignore-optional --non-interactive
warning ../../package.json: No license field
warning "ember-build-utilities@0.4.0" has incorrect peer dependency "@glimmer/compiler@> 0.26.0".
warning "@glimmer/inline-precompile@1.0.1" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "babel-plugin-glimmer-inline-precompile@1.2.0" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/test-helpers@0.30.0" has incorrect peer dependency "@glimmer/component@>= 0.4.0".
error /Users/developers/Projects/glimmer-test/node_modules/broccoli-sass-source-maps/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/developers/Projects/glimmer-test/node_modules/broccoli-sass-source-maps/node_modules/node-sass
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developers/Projects/glimmer-test/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

yarn install v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Command failed: yarn install --ignore-optional --non-interactive
warning ../../package.json: No license field
warning "ember-build-utilities@0.4.0" has incorrect peer dependency "@glimmer/compiler@> 0.26.0".
warning "@glimmer/inline-precompile@1.0.1" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "babel-plugin-glimmer-inline-precompile@1.2.0" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/test-helpers@0.30.0" has incorrect peer dependency "@glimmer/component@>= 0.4.0".
error /Users/developers/Projects/glimmer-test/node_modules/broccoli-sass-source-maps/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/developers/Projects/glimmer-test/node_modules/broccoli-sass-source-maps/node_modules/node-sass
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developers/Projects/glimmer-test/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

yarn install v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (/usr/local/lib/node_modules/ember-cli/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by acorncom** [comment]
@zackkrida Are you still seeing this issue?

**Comment by zackkrida** [comment]
@acorncom nope appears to be resolved, thanks! 👌

**Comment by xpat** [comment]
This doesn't appear resolved as far as I can tell.  Several different commands later, and not one has installed glimmer.  

   66  ember new my-app -b @glimmer/blueprint
   86  ember new my-app -b @glimmer/blueprint
   89  ember new my-app -b @glimmer/blueprint
  256  ember new my-app -b @glimmer/blueprint
  264  ember new my-app -b @glimmer/blueprint
  268  ember new my-app -b @glimmer-blueprint
  270  ember new hello-glimmer -b @glimmer/blueprint
  271  ember new hello-glimmer -b @glimmer/blueprint  --yarn=false
  272  ember new my-app -b https://github.com/glimmerjs/glimmer-blueprint.git
  273  ember new my-app -b https://github.com/glimmerjs/glimmer-blueprint.gi
  274  history | grep "glimmer"
  275  history | grep "glimmer" > glimmer.txt

All of them yield an error message similar to the one initially posted here by zackkrida.  See attached file.
[glimmerErrors.txt](https://github.com/glimmerjs/glimmer-blueprint/files/1540555/glimmerErrors.txt)
